import { FormEvent, useState } from "react";
import { Check, ExternalLink, PauseCircle, Pencil, PlayCircle, Trash2, X } from "lucide-react";
import { Card, EmptyState, Field } from "../../components/ui";
import { recurrenceFormSchema, subscriptionFormSchema, type RecurrenceFormInput, type SubscriptionFormInput } from "../../schemas";
import { financeService } from "../../services/finance";
import { formatDate, todayIso } from "../../lib/format";
import type { Category, RecurringRule, Subscription } from "../../types";

const recBlank=(timezone:string):RecurrenceFormInput=>{const today=todayIso(timezone);return{description:"",amount:0,kind:"expense",category_id:null,frequency:"monthly",interval_count:1,anchor_day:Number(today.slice(8,10)),start_date:today,next_date:today,end_date:null,auto_post:true,active:true,note:null}};
const subBlank=(timezone:string):SubscriptionFormInput=>{const today=todayIso(timezone);return{name:"",amount:0,category_id:null,cycle:"monthly",interval_count:1,billing_day:Number(today.slice(8,10)),start_date:today,next_charge:today,end_date:null,active:true,auto_post:true,reminder_days:3,website:null,note:null}};

export function AutomationsView({rules,subscriptions,categories,money,busy,run,remove,locale,timezone}:{rules:RecurringRule[];subscriptions:Subscription[];categories:Category[];money:(value:number)=>string;busy:boolean;run:(action:()=>Promise<unknown>,message:string)=>Promise<boolean>;remove:(action:()=>Promise<void>)=>Promise<void>;locale:string;timezone:string}){
 const[rec,setRec]=useState<RecurrenceFormInput>(()=>recBlank(timezone));const[recId,setRecId]=useState<string|null>(null);const[sub,setSub]=useState<SubscriptionFormInput>(()=>subBlank(timezone));const[subId,setSubId]=useState<string|null>(null);const[error,setError]=useState("");
 const cat=(kind:"income"|"expense")=>categories.filter(c=>!c.archived&&(c.scope==="both"||c.scope===kind));
 function editRec(item:RecurringRule){setRecId(item.id);setRec({description:item.description,amount:item.amount,kind:item.kind,category_id:item.category_id,frequency:item.frequency,interval_count:item.interval_count,anchor_day:item.anchor_day,start_date:item.start_date,next_date:item.next_date,end_date:item.end_date,auto_post:item.auto_post,active:item.active,note:item.note});setError("");window.scrollTo({top:0,behavior:"smooth"})}
 function editSub(item:Subscription){setSubId(item.id);setSub({name:item.name,amount:item.amount,category_id:item.category_id,cycle:item.cycle,interval_count:item.interval_count,billing_day:item.billing_day,start_date:item.start_date,next_charge:item.next_charge,end_date:item.end_date,active:item.active,auto_post:item.auto_post,reminder_days:item.reminder_days,website:item.website,note:item.note});setError("");window.scrollTo({top:0,behavior:"smooth"})}
 async function saveRec(event:FormEvent){event.preventDefault();const parsed=recurrenceFormSchema.safeParse(rec);if(!parsed.success)return setError(parsed.error.issues[0]?.message??"Confira a recorrência.");if(await run(()=>financeService.saveRecurrence(parsed.data,recId??undefined),recId?"Recorrência atualizada.":"Recorrência criada.")){setRec(recBlank(timezone));setRecId(null);setError("")}}
 async function saveSub(event:FormEvent){event.preventDefault();const parsed=subscriptionFormSchema.safeParse(sub);if(!parsed.success)return setError(parsed.error.issues[0]?.message??"Confira a assinatura.");if(await run(()=>financeService.saveSubscription(parsed.data,subId??undefined),subId?"Assinatura atualizada.":"Assinatura criada.")){setSub(subBlank(timezone));setSubId(null);setError("")}}
 return <div className="two automation-grid">
 <Card title={recId?"Editar recorrência":"Nova recorrência"} subtitle="Para salário, aluguel, contas e qualquer repetição"><form className="grid compact-grid" onSubmit={saveRec} noValidate>
 <Field label="Descrição"><input value={rec.description} maxLength={160} onChange={e=>setRec({...rec,description:e.target.value})} required/></Field><Field label="Valor"><input type="number" min="0.01" step="0.01" value={rec.amount||""} onChange={e=>setRec({...rec,amount:e.target.valueAsNumber})} required/></Field><Field label="Tipo"><select value={rec.kind} onChange={e=>setRec({...rec,kind:e.target.value as "income"|"expense",category_id:null})}><option value="expense">Saída</option><option value="income">Entrada</option></select></Field><Field label="Categoria"><select value={rec.category_id??""} onChange={e=>setRec({...rec,category_id:e.target.value||null})}><option value="">Sem categoria</option>{cat(rec.kind).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Frequência"><select value={rec.frequency} onChange={e=>setRec({...rec,frequency:e.target.value as RecurrenceFormInput["frequency"]})}><option value="daily">Diária</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></Field><Field label="A cada"><input type="number" min="1" max="365" value={rec.interval_count} onChange={e=>setRec({...rec,interval_count:e.target.valueAsNumber})}/></Field><Field label="Início"><input type="date" value={rec.start_date} onChange={e=>setRec({...rec,start_date:e.target.value})}/></Field><Field label="Próxima ocorrência"><input type="date" value={rec.next_date} onChange={e=>setRec({...rec,next_date:e.target.value})}/></Field><Field label="Data final"><input type="date" value={rec.end_date??""} onChange={e=>setRec({...rec,end_date:e.target.value||null})}/></Field><Field label="Dia-base"><input type="number" min="1" max="31" value={rec.anchor_day} onChange={e=>setRec({...rec,anchor_day:e.target.valueAsNumber})}/></Field><Field label="Observação"><textarea maxLength={2000} value={rec.note??""} onChange={e=>setRec({...rec,note:e.target.value||null})}/></Field><label className="check"><input type="checkbox" checked={rec.auto_post} onChange={e=>setRec({...rec,auto_post:e.target.checked})}/>Criar lançamento automaticamente</label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="primary" disabled={busy}><Check size={16}/>{recId?"Salvar":"Criar"}</button>{recId&&<button type="button" className="secondary" onClick={()=>{setRec(recBlank(timezone));setRecId(null)}}><X size={16}/>Cancelar</button>}</div></form>
 {rules.length?<ul className="list automation-list">{rules.map(item=><li key={item.id}><div><b>{item.description}</b><small>{money(item.amount)} · próxima em {formatDate(item.next_date,locale)} · {item.end_date?`até ${formatDate(item.end_date,locale)} · `:""}{item.active?"ativa":"pausada"}</small>{item.note&&<small>{item.note}</small>}</div><div className="row-actions"><button type="button" className="icon" onClick={()=>run(()=>financeService.patchRecurrence(item.id,{active:!item.active}),item.active?"Recorrência pausada.":"Recorrência ativada.")} aria-label={`${item.active?"Pausar":"Ativar"} recorrência ${item.description}`}>{item.active?<PauseCircle size={16}/>:<PlayCircle size={16}/>}</button><button type="button" className="icon" onClick={()=>editRec(item)} aria-label={`Editar recorrência ${item.description}`}><Pencil size={16}/></button><button type="button" className="icon danger-icon" onClick={()=>remove(()=>financeService.deleteRecurrence(item.id))} aria-label={`Excluir recorrência ${item.description}`}><Trash2 size={16}/></button></div></li>)}</ul>:<EmptyState title="Sem recorrências" description="Crie uma regra para não digitar o mesmo lançamento todo mês."/>}</Card>

 <Card title={subId?"Editar assinatura":"Nova assinatura"} subtitle="Acompanhe serviços e datas de cobrança"><form className="grid compact-grid" onSubmit={saveSub} noValidate>
 <Field label="Serviço"><input value={sub.name} maxLength={120} onChange={e=>setSub({...sub,name:e.target.value})} required/></Field><Field label="Valor"><input type="number" min="0.01" step="0.01" value={sub.amount||""} onChange={e=>setSub({...sub,amount:e.target.valueAsNumber})} required/></Field><Field label="Categoria"><select value={sub.category_id??""} onChange={e=>setSub({...sub,category_id:e.target.value||null})}><option value="">Sem categoria</option>{cat("expense").map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="Ciclo"><select value={sub.cycle} onChange={e=>setSub({...sub,cycle:e.target.value as "monthly"|"yearly"})}><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></Field><Field label="A cada"><input type="number" min="1" max="120" value={sub.interval_count} onChange={e=>setSub({...sub,interval_count:e.target.valueAsNumber})}/></Field><Field label="Início"><input type="date" value={sub.start_date} onChange={e=>setSub({...sub,start_date:e.target.value})}/></Field><Field label="Próxima cobrança"><input type="date" value={sub.next_charge} onChange={e=>setSub({...sub,next_charge:e.target.value})}/></Field><Field label="Data final"><input type="date" value={sub.end_date??""} onChange={e=>setSub({...sub,end_date:e.target.value||null})}/></Field><Field label="Dia da cobrança"><input type="number" min="1" max="31" value={sub.billing_day} onChange={e=>setSub({...sub,billing_day:e.target.valueAsNumber})}/></Field><Field label="Avisar antes"><input type="number" min="0" max="60" value={sub.reminder_days} onChange={e=>setSub({...sub,reminder_days:e.target.valueAsNumber})}/></Field><Field label="Site"><input type="url" value={sub.website??""} onChange={e=>setSub({...sub,website:e.target.value||null})} placeholder="https://"/></Field><Field label="Observação"><textarea maxLength={2000} value={sub.note??""} onChange={e=>setSub({...sub,note:e.target.value||null})}/></Field><label className="check"><input type="checkbox" checked={sub.auto_post} onChange={e=>setSub({...sub,auto_post:e.target.checked})}/>Criar lançamento automaticamente</label><div className="form-actions"><button className="primary" disabled={busy}><Check size={16}/>{subId?"Salvar":"Criar"}</button>{subId&&<button type="button" className="secondary" onClick={()=>{setSub(subBlank(timezone));setSubId(null)}}><X size={16}/>Cancelar</button>}</div></form>
 {subscriptions.length?<ul className="list automation-list">{subscriptions.map(item=><li key={item.id}><div><b>{item.name}</b><small>{money(item.amount)} · {formatDate(item.next_charge,locale)} · a cada {item.interval_count} {item.cycle==="monthly"?"mês(es)":"ano(s)"} · {item.active?"ativa":"pausada"}</small>{item.website&&<a href={item.website} target="_blank" rel="noreferrer" className="muted">Abrir site <ExternalLink size={13}/></a>}{item.note&&<small>{item.note}</small>}</div><div className="row-actions"><button type="button" className="icon" onClick={()=>run(()=>financeService.patchSubscription(item.id,{active:!item.active}),item.active?"Assinatura pausada.":"Assinatura ativada.")} aria-label={`${item.active?"Pausar":"Ativar"} assinatura ${item.name}`}>{item.active?<PauseCircle size={16}/>:<PlayCircle size={16}/>}</button><button type="button" className="icon" onClick={()=>editSub(item)} aria-label={`Editar assinatura ${item.name}`}><Pencil size={16}/></button><button type="button" className="icon danger-icon" onClick={()=>remove(()=>financeService.deleteSubscription(item.id))} aria-label={`Excluir assinatura ${item.name}`}><Trash2 size={16}/></button></div></li>)}</ul>:<EmptyState title="Sem assinaturas" description="Cadastre streaming, internet, nuvem e outros serviços recorrentes."/>}</Card></div>;
}
