import { ArrowDownRight, ArrowUpRight, CalendarClock, TrendingUp } from "lucide-react";
import { Card, EmptyState } from "../../components/ui";
import { formatDate, monthLabel } from "../../lib/format";
import type { Category, MonthSummary, Subscription, Transaction } from "../../types";

export function DashboardView({month,onMonth,summary,rows,subscriptions,categoryMap,money,privacy,locale}:{month:string;onMonth:(month:string)=>void;summary:MonthSummary;rows:Transaction[];subscriptions:Subscription[];categoryMap:Map<string,Category>;money:(value:number)=>string;privacy:boolean;locale:string}){
 const upcoming=subscriptions.filter(item=>item.active).slice().sort((a,b)=>a.next_charge.localeCompare(b.next_charge)).slice(0,5);const percent=new Intl.NumberFormat(locale,{minimumFractionDigits:1,maximumFractionDigits:1}).format(summary.savingsRate);
 return <><section className="hero"><div><p>Competência</p><h2>{monthLabel(month,locale)}</h2><small>{privacy?"Valores ocultos pelo modo de privacidade":"Realizado e planejado separados"}</small></div><input aria-label="Selecionar competência" type="month" value={month} onChange={event=>onMonth(event.target.value)}/></section>
 <div className="metrics"><Card title="Entradas" className="metric"><span className="metric-icon good-bg"><ArrowUpRight/></span><strong className="good">{money(summary.income)}</strong><small>Recebido no mês</small></Card><Card title="Saídas" className="metric"><span className="metric-icon bad-bg"><ArrowDownRight/></span><strong className="bad">{money(summary.expense)}</strong><small>Pago no mês</small></Card><Card title="Saldo" className="metric"><span className="metric-icon accent-bg"><TrendingUp/></span><strong>{money(summary.balance)}</strong><small>{percent}% de taxa de poupança</small></Card><Card title="Previsão líquida" className="metric"><span className="metric-icon warning-bg"><CalendarClock/></span><strong>{money(summary.plannedIncome-summary.plannedExpense)}</strong><small>Próximos lançamentos previstos</small></Card></div>
 <div className="two dashboard-grid"><Card title="Últimos lançamentos" subtitle="Movimentos da competência selecionada">{rows.length?<ul className="list">{rows.slice().sort((a,b)=>b.transaction_date.localeCompare(a.transaction_date)).slice(0,8).map(item=><li key={item.id}><div><b>{item.description}</b><small>{formatDate(item.transaction_date,locale)} · {categoryMap.get(item.category_id??"")?.name??"Sem categoria"} · {item.status==="posted"?"realizado":"previsto"}</small></div><strong className={item.kind==="income"?"good":"bad"}>{item.kind==="income"?"+":"-"}{money(item.amount)}</strong></li>)}</ul>:<EmptyState title="Mês limpo" description="Adicione seu primeiro lançamento para começar a leitura financeira."/>}</Card><Card title="Próximas assinaturas" subtitle="Cobranças recorrentes mais próximas">{upcoming.length?<ul className="list">{upcoming.map(item=><li key={item.id}><div><b>{item.name}</b><small>{formatDate(item.next_charge,locale)} · {item.cycle==="monthly"?"mensal":"anual"}</small></div><strong>{money(item.amount)}</strong></li>)}</ul>:<EmptyState title="Nenhuma assinatura" description="Cadastre serviços recorrentes para não ser surpreendido pelas cobranças."/>}</Card></div></>;
}
