import { FormEvent, useEffect, useState } from "react";
import { Archive, AtSign, KeyRound, Laptop, Moon, Pencil, Shield, Sun, Trash2, UserRound, X } from "lucide-react";
import { Card, Field, StatusMessage } from "../../components/ui";
import { emailChangeSchema, passwordChangeSchema, profileFormSchema } from "../../schemas";
import { authService, financeService } from "../../services/finance";
import { PasswordField } from "../auth/PasswordField";
import type { Category, Profile, ThemeMode, UserSettings } from "../../types";

export function SettingsView({ profile, settings, categories, email, busy, run, refresh, remove }:{profile:Profile|null;settings:UserSettings|null;categories:Category[];email:string;busy:boolean;run:(action:()=>Promise<unknown>,message:string)=>Promise<boolean>;refresh:()=>Promise<void>;remove:(action:()=>Promise<void>)=>Promise<void>}){
  const[profileForm,setProfileForm]=useState({display_name:"",currency:"BRL",locale:"pt-BR",timezone:"America/Porto_Velho"});
  const[emailForm,setEmailForm]=useState({email:"",confirmation:""});
  const[passwordForm,setPasswordForm]=useState({currentPassword:"",password:"",confirmation:""});
  const[category,setCategory]=useState({name:"",scope:"both" as "income"|"expense"|"both",color:"#22c55e",archived:false});
  const[categoryId,setCategoryId]=useState<string|null>(null);const[feedback,setFeedback]=useState("");const[tone,setTone]=useState<"success"|"error"|"info">("info");
  useEffect(()=>{if(profile)setProfileForm({display_name:profile.display_name,currency:profile.currency,locale:profile.locale,timezone:profile.timezone})},[profile]);
  async function saveProfile(event:FormEvent){event.preventDefault();const parsed=profileFormSchema.safeParse(profileForm);if(!parsed.success)return fail(parsed.error.issues[0]?.message??"Confira o perfil.");await run(()=>financeService.updateProfile(parsed.data),"Perfil atualizado.")}
  async function saveEmail(event:FormEvent){event.preventDefault();const parsed=emailChangeSchema.safeParse(emailForm);if(!parsed.success)return fail(parsed.error.issues[0]?.message??"Confira os e-mails.");try{await authService.updateEmail(parsed.data.email);setTone("success");setFeedback("Enviamos a confirmação para o novo e-mail. O endereço atual permanece válido até a confirmação.");setEmailForm({email:"",confirmation:""})}catch(caught){fail(caught instanceof Error?caught.message:"Não foi possível alterar o e-mail.")}}
  async function savePassword(event:FormEvent){event.preventDefault();const parsed=passwordChangeSchema.safeParse(passwordForm);if(!parsed.success)return fail(parsed.error.issues[0]?.message??"Confira as senhas.");try{await authService.updatePassword(parsed.data.currentPassword,parsed.data.password);setTone("success");setFeedback("Senha alterada com sucesso.");setPasswordForm({currentPassword:"",password:"",confirmation:""})}catch(caught){fail(caught instanceof Error?caught.message:"Não foi possível alterar a senha.")}}
  function fail(message:string){setTone("error");setFeedback(message)}
  async function setTheme(theme:ThemeMode){document.documentElement.dataset.theme=theme==="light"?"light":"dark";await run(()=>financeService.updateSettings({theme}),"Tema atualizado.")}
  async function saveCategory(event:FormEvent){event.preventDefault();if(category.name.trim().length<1)return fail("Informe o nome da categoria.");if(await run(()=>financeService.saveCategory({...category,name:category.name.trim()},categoryId??undefined),categoryId?"Categoria atualizada.":"Categoria criada.")){setCategory({name:"",scope:"both",color:"#22c55e",archived:false});setCategoryId(null);await refresh()}}
  function editCategory(item:Category){setCategoryId(item.id);setCategory({name:item.name,scope:item.scope,color:item.color,archived:item.archived})}
  return <div className="settings-stack">{feedback&&<StatusMessage tone={tone}>{feedback}</StatusMessage>}
    <div className="two"><Card title="Perfil" subtitle="Informações usadas na interface" actions={<UserRound size={20}/>}><form className="grid compact-grid" onSubmit={saveProfile}><Field label="Nome"><input value={profileForm.display_name} onChange={e=>setProfileForm({...profileForm,display_name:e.target.value})} maxLength={80}/></Field><Field label="Moeda"><input value={profileForm.currency} onChange={e=>setProfileForm({...profileForm,currency:e.target.value.toUpperCase()})} maxLength={3}/></Field><Field label="Idioma"><input value={profileForm.locale} onChange={e=>setProfileForm({...profileForm,locale:e.target.value})}/></Field><Field label="Fuso horário"><select value={profileForm.timezone} onChange={e=>setProfileForm({...profileForm,timezone:e.target.value})}><option value="America/Porto_Velho">Rondônia / Manaus</option><option value="America/Sao_Paulo">Brasília / São Paulo</option><option value="America/Rio_Branco">Acre</option><option value="UTC">UTC</option></select></Field><button className="primary" disabled={busy}>Salvar perfil</button></form></Card>
    <Card title="Aparência e privacidade" subtitle="O escuro neon é o padrão" actions={settings?.theme==="light"?<Sun size={20}/>:<Moon size={20}/>}><div className="theme-picker"><button className={settings?.theme!=="light"?"selected":""} onClick={()=>setTheme("dark")}><Moon/>Escuro neon<small>Contraste alto e verde elétrico</small></button><button className={settings?.theme==="light"?"selected":""} onClick={()=>setTheme("light")}><Sun/>Claro aurora<small>Fundo luminoso e acentos esmeralda</small></button></div><label className="switch-row"><span><b>Ocultar valores</b><small>Esconde números financeiros sem apagar dados</small></span><input type="checkbox" checked={settings?.privacy_mode??false} onChange={e=>run(()=>financeService.updateSettings({privacy_mode:e.target.checked}),"Privacidade atualizada.")}/></label><label className="switch-row"><span><b>Modo compacto</b><small>Reduz espaçamentos em telas densas</small></span><input type="checkbox" checked={settings?.compact_mode??false} onChange={e=>run(()=>financeService.updateSettings({compact_mode:e.target.checked}),"Densidade atualizada.")}/></label></Card></div>
    <div className="two"><Card title="E-mail da conta" subtitle={`Atual: ${email}`} actions={<AtSign size={20}/>}><form onSubmit={saveEmail} className="stack-form"><Field label="Novo e-mail"><input type="email" value={emailForm.email} onChange={e=>setEmailForm({...emailForm,email:e.target.value})} autoComplete="email"/></Field><Field label="Confirmar novo e-mail"><input type="email" value={emailForm.confirmation} onChange={e=>setEmailForm({...emailForm,confirmation:e.target.value})} autoComplete="email"/></Field><button className="primary" disabled={busy}>Solicitar alteração</button><p className="muted">A alteração só termina depois da confirmação por e-mail.</p></form></Card>
    <Card title="Alterar senha" subtitle="A senha atual é obrigatória" actions={<KeyRound size={20}/>}><form onSubmit={savePassword} className="stack-form"><PasswordField label="Senha atual" value={passwordForm.currentPassword} onChange={value=>setPasswordForm({...passwordForm,currentPassword:value})} autoComplete="current-password"/><PasswordField label="Nova senha" value={passwordForm.password} onChange={value=>setPasswordForm({...passwordForm,password:value})} autoComplete="new-password" showRules/><PasswordField label="Confirmar nova senha" value={passwordForm.confirmation} onChange={value=>setPasswordForm({...passwordForm,confirmation:value})} autoComplete="new-password"/><button className="primary" disabled={busy}>Alterar senha</button></form></Card></div>
    <Card title="Sessões" subtitle="Controle onde sua conta permanece conectada" actions={<Laptop size={20}/>}><div className="session-actions"><button className="secondary" onClick={()=>authService.signOut("others")}><Shield size={17}/>Sair de outros dispositivos</button><button className="danger" onClick={()=>authService.signOut("global")}><Laptop size={17}/>Sair de todos os dispositivos</button></div><p className="muted">Tokens de acesso já emitidos expiram automaticamente. A revogação encerra os tokens de atualização.</p></Card>
    <Card title="Categorias" subtitle="Edite, arquive ou exclua categorias não utilizadas"><form className="grid" onSubmit={saveCategory}><Field label="Nome"><input value={category.name} onChange={e=>setCategory({...category,name:e.target.value})} maxLength={60}/></Field><Field label="Uso"><select value={category.scope} onChange={e=>setCategory({...category,scope:e.target.value as typeof category.scope})}><option value="both">Entradas e saídas</option><option value="income">Entradas</option><option value="expense">Saídas</option></select></Field><Field label="Cor"><input type="color" value={category.color} onChange={e=>setCategory({...category,color:e.target.value})}/></Field><div className="form-actions"><button className="primary" disabled={busy}>{categoryId?"Salvar categoria":"Adicionar categoria"}</button>{categoryId&&<button type="button" className="secondary" onClick={()=>{setCategoryId(null);setCategory({name:"",scope:"both",color:"#22c55e",archived:false})}}><X size={16}/>Cancelar</button>}</div></form><ul className="list category-list">{categories.map(item=><li key={item.id}><div><span className="category-dot" style={{background:item.color}}/><div><b>{item.name}</b><small>{item.archived?"arquivada":item.scope==="both"?"entradas e saídas":item.scope==="income"?"entradas":"saídas"}</small></div></div><div className="row-actions"><button className="icon" onClick={()=>run(()=>financeService.saveCategory({name:item.name,scope:item.scope,color:item.color,archived:!item.archived},item.id),item.archived?"Categoria restaurada.":"Categoria arquivada.")} aria-label={item.archived?"Restaurar categoria":"Arquivar categoria"}><Archive size={16}/></button><button className="icon" onClick={()=>editCategory(item)} aria-label="Editar categoria"><Pencil size={16}/></button><button className="icon danger-icon" onClick={()=>remove(()=>financeService.deleteCategory(item.id))} aria-label="Excluir categoria"><Trash2 size={16}/></button></div></li>)}</ul></Card>
  </div>
}
