import { FormEvent, useEffect, useState } from "react";
import { Pencil, Trash2, X } from "lucide-react";
import { Card, EmptyState, Field } from "../../components/ui";
import { budgetFormSchema, type BudgetFormInput } from "../../schemas";
import { financeService } from "../../services/finance";
import type { Budget, BudgetStatus, Category } from "../../types";

interface Props{month:string;budgets:Budget[];categories:Category[];money:(value:number)=>string;busy:boolean;run:(action:()=>Promise<unknown>,message:string)=>Promise<boolean>;remove:(action:()=>Promise<void>)=>Promise<void>}
const blank=(month:string):BudgetFormInput=>({category_id:"",month:`${month}-01`,amount:0,rollover:false});
export function BudgetsView({month,budgets,categories,money,busy,run,remove}:Props){
 const[form,setForm]=useState<BudgetFormInput>(()=>blank(month));const[editing,setEditing]=useState<string|null>(null);const[error,setError]=useState("");const[status,setStatus]=useState<BudgetStatus[]>([]);const[statusError,setStatusError]=useState("");
 const monthBudgets=budgets.filter(item=>item.month.startsWith(month));const categoryMap=new Map(categories.map(item=>[item.id,item]));const statusMap=new Map(status.map(item=>[item.category_id,item]));
 useEffect(()=>{let active=true;setStatusError("");void financeService.getBudgetStatus(`${month}-01`).then(data=>{if(active)setStatus(data)}).catch(caught=>{if(active)setStatusError(caught instanceof Error?caught.message:"Não foi possível calcular o rollover.")});return()=>{active=false}},[month,budgets]);
 function cancel(){setEditing(null);setForm(blank(month));setError("")}
 function edit(item:Budget){setEditing(item.id);setForm({category_id:item.category_id,month:item.month,amount:item.amount,rollover:item.rollover})}
 async function submit(event:FormEvent){event.preventDefault();const parsed=budgetFormSchema.safeParse(form);if(!parsed.success){setError(parsed.error.issues[0]?.message??"Confira o orçamento.");return}if(await run(()=>financeService.saveBudget(parsed.data,editing??undefined),editing?"Orçamento atualizado.":"Orçamento salvo."))cancel()}
 return <><Card title={editing?"Editar orçamento":"Orçamento mensal"} subtitle="O saldo positivo pode ser carregado para o próximo mês"><form className="grid" onSubmit={submit} noValidate><Field label="Categoria"><select value={form.category_id} onChange={event=>setForm({...form,category_id:event.target.value})} required disabled={busy}><option value="">Selecione</option>{categories.filter(category=>!category.archived&&(category.scope==="expense"||category.scope==="both")).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Mês"><input type="month" value={form.month.slice(0,7)} onChange={event=>setForm({...form,month:`${event.target.value}-01`})} disabled={busy}/></Field><Field label="Limite"><input type="number" min="0.01" step="0.01" value={form.amount||""} onChange={event=>setForm({...form,amount:event.target.valueAsNumber})} disabled={busy}/></Field><label className="check"><input type="checkbox" checked={form.rollover} onChange={event=>setForm({...form,rollover:event.target.checked})} disabled={busy}/>Carregar saldo positivo não usado para o mês seguinte</label>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="primary" disabled={busy}>{editing?"Salvar alteração":"Salvar orçamento"}</button>{editing&&<button type="button" className="secondary" onClick={cancel} disabled={busy}><X size={16}/>Cancelar</button>}</div></form></Card>
 {statusError&&<p className="form-error" role="alert">{statusError}</p>}
 {monthBudgets.length?<div className="metrics budget-cards">{monthBudgets.map(item=>{const calculated=statusMap.get(item.category_id);const spent=calculated?.spent??0;const effective=calculated?.effective_amount??item.amount;const remaining=calculated?.remaining??effective-spent;const exceeded=remaining<0;const ratio=effective>0?Math.min(100,(spent/effective)*100):0;return <Card key={item.id} title={categoryMap.get(item.category_id)?.name??"Categoria"} actions={<div className="row-actions"><button type="button" className="icon" onClick={()=>edit(item)} aria-label={`Editar orçamento de ${categoryMap.get(item.category_id)?.name??"categoria"}`} disabled={busy}><Pencil size={16}/></button><button type="button" className="icon danger-icon" onClick={()=>remove(()=>financeService.deleteBudget(item.id))} aria-label={`Excluir orçamento de ${categoryMap.get(item.category_id)?.name??"categoria"}`} disabled={busy}><Trash2 size={16}/></button></div>}><strong>{money(spent)} <small>/ {money(effective)}</small></strong>{(calculated?.rollover_amount??0)>0&&<small>Inclui {money(calculated?.rollover_amount??0)} carregados</small>}<div className="progress" role="progressbar" aria-label="Uso do orçamento" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(ratio)}><span style={{width:`${ratio}%`}}/></div><p className={exceeded?"bad":"muted"}>{exceeded?`Excedido em ${money(Math.abs(remaining))}`:`Restam ${money(remaining)}`}</p></Card>})}</div>:<Card title="Orçamentos"><EmptyState title="Nenhum limite neste mês" description="Crie um orçamento por categoria para enxergar desvios antes do fim do mês."/></Card>}</>;
}
