import { z } from "zod";
import { passwordSchema } from "./features/auth/password";

export const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Informe uma data válida.").refine(value => { const [year,month,day]=value.split("-").map(Number);if(!year||!month||!day)return false;const date=new Date(Date.UTC(year,month-1,day));return date.getUTCFullYear()===year&&date.getUTCMonth()===month-1&&date.getUTCDate()===day; },"Informe uma data existente.");
const amount=z.number().finite().positive("O valor deve ser maior que zero.").max(999_999_999_999.99,"O valor excede o limite suportado.");const optionalUuid=z.string().uuid().nullable();const note=z.string().trim().max(2000,"A observação deve ter até 2.000 caracteres.").nullable();
export const transactionFormSchema=z.object({description:z.string().trim().min(1,"Informe uma descrição.").max(160),amount,kind:z.enum(["income","expense"]),status:z.enum(["planned","posted"]),category_id:optionalUuid,transaction_date:isoDate,note}).strict();
export const recurrenceFormSchema=z.object({description:z.string().trim().min(1,"Informe uma descrição.").max(160),amount,kind:z.enum(["income","expense"]),category_id:optionalUuid,frequency:z.enum(["daily","weekly","monthly","yearly"]),interval_count:z.number().int().min(1).max(365),anchor_day:z.number().int().min(1).max(31),start_date:isoDate,next_date:isoDate,end_date:isoDate.nullable(),auto_post:z.boolean(),active:z.boolean(),note}).strict().superRefine((value,context)=>{if(value.next_date<value.start_date)context.addIssue({code:"custom",path:["next_date"],message:"A próxima data não pode vir antes do início."});if(value.end_date&&value.end_date<value.start_date)context.addIssue({code:"custom",path:["end_date"],message:"O fim não pode vir antes do início."})});
export const subscriptionFormSchema=z.object({name:z.string().trim().min(1,"Informe o serviço.").max(120),amount,category_id:optionalUuid,cycle:z.enum(["monthly","yearly"]),interval_count:z.number().int().min(1).max(120),billing_day:z.number().int().min(1).max(31),start_date:isoDate,next_charge:isoDate,end_date:isoDate.nullable(),active:z.boolean(),auto_post:z.boolean(),reminder_days:z.number().int().min(0).max(60),website:z.union([z.string().url("Informe uma URL válida.").max(500),z.literal(""),z.null()]).transform(value=>value||null),note}).strict().superRefine((value,context)=>{if(value.next_charge<value.start_date)context.addIssue({code:"custom",path:["next_charge"],message:"A próxima cobrança não pode vir antes do início."});if(value.end_date&&value.end_date<value.start_date)context.addIssue({code:"custom",path:["end_date"],message:"O fim não pode vir antes do início."})});
export const budgetFormSchema=z.object({category_id:z.string().uuid("Selecione uma categoria."),month:z.string().regex(/^\d{4}-\d{2}-01$/),amount,rollover:z.boolean()}).strict();
export const profileFormSchema=z.object({display_name:z.string().trim().min(2,"Informe seu nome.").max(80),currency:z.string().regex(/^[A-Z]{3}$/,"Use uma moeda ISO de três letras."),locale:z.string().trim().min(2).max(20),timezone:z.string().trim().min(1).max(64)}).strict();
export const emailChangeSchema=z.object({email:z.string().trim().email("Informe um e-mail válido.").max(254),confirmation:z.string().trim().email()}).strict().refine(value=>value.email.toLowerCase()===value.confirmation.toLowerCase(),{path:["confirmation"],message:"Os e-mails não coincidem."});
export const passwordChangeSchema=z.object({currentPassword:z.string().min(1,"Informe a senha atual."),password:passwordSchema,confirmation:z.string()}).strict().refine(value=>value.password===value.confirmation,{path:["confirmation"],message:"As senhas não coincidem."}).refine(value=>value.password!==value.currentPassword,{path:["password"],message:"A nova senha deve ser diferente da atual."});
export type TransactionFormInput=z.input<typeof transactionFormSchema>;export type RecurrenceFormInput=z.input<typeof recurrenceFormSchema>;export type SubscriptionFormInput=z.input<typeof subscriptionFormSchema>;export type BudgetFormInput=z.input<typeof budgetFormSchema>;
