import { FormEvent, useMemo, useState } from "react";
import { Check, Pencil, Plus, Search, Trash2, X } from "lucide-react";
import { Card, EmptyState, Field } from "../../components/ui";
import { transactionFormSchema, type TransactionFormInput } from "../../schemas";
import { financeService } from "../../services/finance";
import { formatDate, todayIso } from "../../lib/format";
import type { Category, Transaction } from "../../types";

const blank=(timezone:string):TransactionFormInput=>({description:"",amount:0,kind:"expense",status:"posted",category_id:null,transaction_date:todayIso(timezone),note:null});
export function TransactionsView({rows,categories,money,busy,run,remove,locale,timezone}:{rows:Transaction[];categories:Category[];money:(value:number)=>string;busy:boolean;run:(action:()=>Promise<unknown>,message:string)=>Promise<boolean>;remove:(action:()=>Promise<void>)=>Promise<void>;locale:string;timezone:string}){
 const[form,setForm]=useState<TransactionFormInput>(()=>blank(timezone));const[editing,setEditing]=useState<string|null>(null);const[query,setQuery]=useState("");const[kind,setKind]=useState<"all"|"income"|"expense">("all");const[validation,setValidation]=useState("");
 const visible=useMemo(()=>rows.filter(item=>(kind==="all"||item.kind===kind)&&`${item.description} ${item.note??""}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.transaction_date.localeCompare(a.transaction_date)),[rows,query,kind]);
 function edit(item:Transaction){setEditing(item.id);setValidation("");setForm({description:item.description,amount:item.amount,kind:item.kind,status:item.status,category_id:item.category_id,transaction_date:item.transaction_date,note:item.note});window.scrollTo({top:0,behavior:"smooth"})}
 function cancel(){setEditing(null);setForm(blank(timezone));setValidation("")}
 async function submit(event:FormEvent){event.preventDefault();const parsed=transactionFormSchema.safeParse(form);if(!parsed.success)return setValidation(parsed.error.issues[0]?.message??"Confira os dados.");if(await run(()=>financeService.saveTransaction(parsed.data,editing??undefined),editing?"Lançamento atualizado.":"Lançamento adicionado."))cancel()}
 const allowed=categories.filter(category=>!category.archived&&(category.scope==="both"||category.scope===form.kind));
 return <><Card title={editing?"Editar lançamento":"Novo lançamento"} subtitle="Separe o que já ocorreu do que ainda está previsto" actions={editing&&<button type="button" className="icon ghost" onClick={cancel} aria-label="Cancelar edição"><X size={18}/></button>}><form className="grid" onSubmit={submit}><Field label="Descrição"><input value={form.description} maxLength={160} onChange={event=>setForm({...form,description:event.target.value})} required/></Field><Field label="Valor"><input type="number" min="0.01" step="0.01" value={form.amount||""} onChange={event=>setForm({...form,amount:event.target.valueAsNumber})} required/></Field><Field label="Tipo"><select value={form.kind} onChange={event=>setForm({...form,kind:event.target.value as "income"|"expense",category_id:null})}><option value="expense">Saída</option><option value="income">Entrada</option></select></Field><Field label="Situação" hint="Previsto não afeta o saldo realizado"><select value={form.status} onChange={event=>setForm({...form,status:event.target.value as "posted"|"planned"})}><option value="posted">Realizado</option><option value="planned">Previsto</option></select></Field><Field label="Data"><input type="date" value={form.transaction_date} onChange={event=>setForm({...form,transaction_date:event.target.value})} required/></Field><Field label="Categoria"><select value={form.category_id??""} onChange={event=>setForm({...form,category_id:event.target.value||null})}><option value="">Sem categoria</option>{allowed.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></Field><Field label="Observação"><textarea value={form.note??""} maxLength={2000} onChange={event=>setForm({...form,note:event.target.value||null})}/></Field>{editing&&rows.find(item=>item.id===editing)?.source!=="manual"&&<p className="muted">Esta é uma ocorrência gerada. A alteração afeta somente este lançamento; a regra de origem continua ativa.</p>}{validation&&<p className="form-error" role="alert">{validation}</p>}<button className="primary" disabled={busy}>{editing?<><Check size={17}/>Salvar alteração</>:<><Plus size={17}/>Adicionar</>}</button></form></Card>
 <Card title="Lançamentos" subtitle={`${visible.length} resultado(s) nesta competência`} actions={<div className="filters"><label className="search"><Search size={16}/><input aria-label="Pesquisar lançamentos" placeholder="Pesquisar" value={query} onChange={event=>setQuery(event.target.value)}/></label><select aria-label="Filtrar por tipo" value={kind} onChange={event=>setKind(event.target.value as typeof kind)}><option value="all">Todos</option><option value="income">Entradas</option><option value="expense">Saídas</option></select></div>}>{visible.length?<div className="table"><table><thead><tr><th>Data</th><th>Descrição</th><th>Situação</th><th>Valor</th><th><span className="sr-only">Ações</span></th></tr></thead><tbody>{visible.map(item=><tr key={item.id}><td>{formatDate(item.transaction_date,locale)}</td><td><b>{item.description}</b>{item.note&&<small>{item.note}</small>}{item.source!=="manual"&&item.source!=="api"&&<small>Gerado por {item.source==="recurrence"?"recorrência":item.source==="subscription"?"assinatura":"importação"}</small>}</td><td><span className={`badge ${item.status}`}>{item.status==="posted"?"Realizado":"Previsto"}</span></td><td className={item.kind==="income"?"good":"bad"}>{item.kind==="income"?"+":"-"}{money(item.amount)}</td><td><div className="row-actions"><button type="button" className="icon" onClick={()=>edit(item)} aria-label={`Editar ${item.description}`}><Pencil size={16}/></button><button type="button" className="icon danger-icon" onClick={()=>remove(()=>financeService.deleteTransaction(item.id))} aria-label={`Excluir ${item.description}; a regra de origem não será alterada`}><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>:<EmptyState title="Nada encontrado" description="Ajuste os filtros ou adicione um lançamento."/>}</Card></>;
}
